name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --only=dev || true
      
    - name: Validate JavaScript files
      run: |
        echo "Validating JavaScript files..."
        # Check for syntax errors in JS files
        find . -name "*.js" -not -path "./node_modules/*" -exec node -c {} \;
        echo "✅ All JavaScript files are valid"
        
    - name: Validate HTML files
      run: |
        echo "Checking HTML files..."
        # Basic HTML validation
        grep -q "<!DOCTYPE html>" index.html && echo "✅ index.html has DOCTYPE"
        grep -q "<!DOCTYPE html>" apply.html && echo "✅ apply.html has DOCTYPE"
        grep -q "<!DOCTYPE html>" reflect.html && echo "✅ reflect.html has DOCTYPE"
        
    - name: Check file structure
      run: |
        echo "Verifying project structure..."
        test -f index.html && echo "✅ index.html exists"
        test -f apply.html && echo "✅ apply.html exists"
        test -f reflect.html && echo "✅ reflect.html exists"
        test -f app.js && echo "✅ app.js exists"
        test -f lotus_core.js && echo "✅ lotus_core.js exists"
        test -f global.js && echo "✅ global.js exists"
        test -f ui-components.js && echo "✅ ui-components.js exists"
        test -f utils.js && echo "✅ utils.js exists"
        test -f autonomy_theater.js && echo "✅ autonomy_theater.js exists"
        test -d assets && echo "✅ assets/ directory exists"
        test -d data && echo "✅ data/ directory exists"
        test -f assets/styles/ethical.css && echo "✅ ethical.css exists"
        test -f assets/styles/deceptive.css && echo "✅ deceptive.css exists"
        test -f data/quiz_bank.json && echo "✅ quiz_bank.json exists"
        test -f data/trap_scenarios.json && echo "✅ trap_scenarios.json exists"
        test -f data/ui_config.json && echo "✅ ui_config.json exists"
        test -f data/usury_laws.json && echo "✅ usury_laws.json exists"
        echo "🎉 All required files present"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Create optimized build
      run: |
        echo "Creating optimized build for GitHub Pages..."
        # Ensure .nojekyll exists
        touch .nojekyll
        # Create a simple optimization log
        echo "Build completed at $(date)" > build.log
        echo "✅ Build optimization complete"
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
